/*
 * $Id: DiscardableProcResult.java,v 1.3 2004-10-01 15:02:22 mhw Exp $
 */

package org.codehaus.tagalog.jdbc;

/**
 * Interface that should be implemented by any object that can be returned
 * from a {@link ProcStatement}, if the object has special requirements
 * to ensure that resources are released properly. This interface is used
 * to release resources returned by an intermediate <code>ProcStatement</code>
 * when a later <code>ProcStatement</code> also returns a result
 * (given that a {@link Proc} only returns that object resulting from
 * the last statement that returns a non-null value).
 * 
 * @author Mark H. Wilkinson
 * @version $Revision: 1.3 $
 */
public interface DiscardableProcResult {
    /**
     * Release all resources associated with this result.
     *
     * @throws ProcException Wrapping any exception generated by discarding
     * the result.
     */
    void discard() throws ProcException;
}
