/*
 * $Id: StatementExpression.java,v 1.1 2005-04-19 16:26:09 mhw Exp $
 */

package org.codehaus.tagalog.script;

import java.io.StringWriter;
import java.util.Map;

import org.codehaus.tagalog.el.Expression;
import org.codehaus.tagalog.el.ExpressionEvaluationException;

/**
 * Wrap a {@link Statement} as an {@link Expression}. The value of the
 * expression is a {@link String} containing the output generated by
 * executing the <code>Statement</code>, if any.
 *
 * @author <a href="mailto:mhw@kremvax.net">Mark Wilkinson</a>
 * @version $Revision: 1.1 $
 */
public final class StatementExpression implements Expression {

    private final Statement statement;

    /**
     * @param statement The statement to wrap as an <code>Expression</code>.
     */
    public StatementExpression(Statement statement) {
        this.statement = statement;
    }

    public Object evaluate(Map context) throws ExpressionEvaluationException {
        StringWriter captureWriter = new StringWriter();
        Object oldWriter = context.put(Script.TAGALOG_OUT, captureWriter);
        try {
            statement.execute(context);
        } catch (Exception e) {
            throw new ExpressionEvaluationException(e);
        } finally {
            context.put(Script.TAGALOG_OUT, oldWriter);
        }
        return captureWriter.toString();
    }
}
